// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.488
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Specs.FluentAlerts.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("A developer can create a table based alert")]
    public partial class ADeveloperCanCreateATableBasedAlertFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DeveloperCanCreateATableBasedAlert.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "A developer can create a table based alert", "In order to document the current system state in a human readable format\r\nAs a de" +
                    "veloper\r\nI want to be able to create a hierarchical table of information", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("I have an alert factory");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can add normal rows to a table")]
        public virtual void CanAddNormalRowsToATable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can add normal rows to a table", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 10
 testRunner.Given("I have a table builder");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Cell1",
                        "Cell2"});
            table1.AddRow(new string[] {
                        "One",
                        "1"});
            table1.AddRow(new string[] {
                        "Two",
                        "2"});
#line 11
 testRunner.When("I add the \'normal\' rows", ((string)(null)), table1);
#line 15
  testRunner.And("I build the alert");
#line 16
 testRunner.Then("the alert should have 2 rows");
#line 17
  testRunner.And("row 1 should be a \'normal\' row");
#line 18
  testRunner.And("row 1 cell 1 should be \'One\'");
#line 19
  testRunner.And("row 1 cell 2 should be \'1\'");
#line 20
  testRunner.And("row 2 should be a \'normal\' row");
#line 21
  testRunner.And("row 2 cell 1 should be \'Two\'");
#line 22
  testRunner.And("row 2 cell 2 should be \'2\'");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can add highlighted rows to a table")]
        public virtual void CanAddHighlightedRowsToATable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can add highlighted rows to a table", ((string[])(null)));
#line 24
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 25
 testRunner.Given("I have a table builder");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Cell1",
                        "Cell2"});
            table2.AddRow(new string[] {
                        "One",
                        "1"});
#line 26
 testRunner.When("I add the \'highlighted\' rows", ((string)(null)), table2);
#line 29
  testRunner.And("I build the alert");
#line 30
 testRunner.Then("the alert should have 1 rows");
#line 31
  testRunner.And("row 1 should be a \'highlighted\' row");
#line 32
  testRunner.And("row 1 cell 1 should be \'One\'");
#line 33
  testRunner.And("row 1 cell 2 should be \'1\'");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can add header rows to a table")]
        public virtual void CanAddHeaderRowsToATable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can add header rows to a table", ((string[])(null)));
#line 35
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 36
 testRunner.Given("I have a table builder");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Cell1"});
            table3.AddRow(new string[] {
                        "One"});
#line 37
 testRunner.When("I add the \'header\' rows", ((string)(null)), table3);
#line 40
  testRunner.And("I build the alert");
#line 41
 testRunner.Then("the alert should have 1 rows");
#line 42
  testRunner.And("row 1 should be a \'header\' row");
#line 43
  testRunner.And("row 1 cell 1 should be \'One\'");
#line 44
  testRunner.And("row 1 should have 1 cells");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can add footer rows to a table")]
        public virtual void CanAddFooterRowsToATable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can add footer rows to a table", ((string[])(null)));
#line 46
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 47
 testRunner.Given("I have a table builder");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Cell1"});
            table4.AddRow(new string[] {
                        "One"});
#line 48
 testRunner.When("I add the \'footer\' rows", ((string)(null)), table4);
#line 51
  testRunner.And("I build the alert");
#line 52
 testRunner.Then("the alert should have 1 rows");
#line 53
  testRunner.And("row 1 should be a \'footer\' row");
#line 54
  testRunner.And("row 1 cell 1 should be \'One\'");
#line 55
  testRunner.And("row 1 should have 1 cells");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can create a table with a title")]
        public virtual void CanCreateATableWithATitle()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can create a table with a title", ((string[])(null)));
#line 57
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 58
 testRunner.Given("I create a table with a title \'some title\'");
#line 59
 testRunner.When("I build the alert");
#line 60
 testRunner.Then("the alert should have 2 columns");
#line 61
  testRunner.And("the alert should have 1 rows");
#line 62
  testRunner.And("row 1 should be a \'header\' row");
#line 63
  testRunner.And("row 1 should have 1 cells");
#line 64
  testRunner.And("row 1 cell 1 should be \'some title\'");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can create a table from an objects property values")]
        public virtual void CanCreateATableFromAnObjectsPropertyValues()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can create a table from an objects property values", ((string[])(null)));
#line 66
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 67
 testRunner.Given("I create a table with an object using depth 0");
#line 68
 testRunner.When("I build the alert");
#line 69
 testRunner.Then("the title is the objects type");
#line 70
  testRunner.And("a row is added for each property with cells for property name and property value");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can create a table from an objects property values recursing reference types exce" +
            "pt strings to a given depth")]
        public virtual void CanCreateATableFromAnObjectsPropertyValuesRecursingReferenceTypesExceptStringsToAGivenDepth()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can create a table from an objects property values recursing reference types exce" +
                    "pt strings to a given depth", ((string[])(null)));
#line 72
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 73
 testRunner.Given("I create a table with an object using depth 3");
#line 74
 testRunner.When("I build the alert");
#line 75
 testRunner.Then("the title is the objects type");
#line 76
  testRunner.And("a row is added for each property with cells for property name and property value");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can create a table from an exception")]
        public virtual void CanCreateATableFromAnException()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can create a table from an exception", ((string[])(null)));
#line 78
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 79
 testRunner.Given("I create a table with an exception");
#line 80
 testRunner.When("I build the alert");
#line 81
 testRunner.Then("the table should have a row for the type, message and stack trace for all excepti" +
                    "on in chain");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
